# 改行を入れない
add_newline = false

# 表示する項目の順番と構成
format = """
$directory\
$git_branch\
$git_status\
$golang\
$dotnet\
$bun\
$nodejs\
${custom.typescript}\
$python\
$custom\
$line_break\
$character"""

[character]
success_symbol = "[❯](bold cyan)"
error_symbol = "[❯](bold red)"

# --- 言語別設定 ---

[golang]
symbol = "󰟓 "
style = "bold cyan"
# go.modがあるディレクトリで表示する
format = "via [$symbol($version )]($style)"

[dotnet]
symbol = " "
style = "bold purple"
# .csprojや.slnがある場所で表示
detect_extensions = ["csproj", "sln"]
format = "via [$symbol($version )]($style)"

# TypeScript 用のカスタム設定
[custom.typescript]
# tsconfig.json がある、または .ts / .tsx ファイルがある場合に表示
detect_files = ["tsconfig.json"]
detect_extensions = ["ts", "tsx"]
symbol = " "
style = "bold blue"
format = "via [$symbol]($style)"

[nodejs]
symbol = " "
style = "bold green"
# package.jsonがある場所で表示
format = "via [$symbol($version )]($style)"
